### ISSUE TITLE
The website is organised, responsive, and easy to navigate

### ISSUE THREAD

**Issue by Mark1-15** [Mark1-15/project-1#1]
**User story:**
As someone who wishes to view this website for the first time, it should be organised, responsive, and easy to navigate, resulting to an excellent user experience.

**Acceptance Criteria:**

- [x] The website has an organised structure, is easy to navigate, and is easy to see on all device sizes.
- [x] The website is responsive and reacts appropriately to user commands.

**Tasks:**

- [x] Create a website with an organised structure and easy navigation in HTML5 and bootstrap, which looks professional on all screen sizes.
- [x] Use appropriate CSS3 to style the website to make it look presentable and professional.
