### ISSUE TITLE
The website is informative, providing all the information users expect

### ISSUE THREAD

**Issue by Mark1-15** [Mark1-15/project-1#2]
**User story:**
I am interested the ideas behind the creation of this website and its potential services, I wish the website to fully informative, with all areas of the page displaying adequate information about the purpose of the website and the services it provides, allowing me to find the information I want easily.

**Acceptance Criteria:**

- [x] The website is fully informative, with the correct information in the correct place that will allow users to easily identify the purpose of this website and the services it offers.

**Tasks:**

- [x] Ensure that all the information about the purpose of the website is on the homepage
- [x] Brief description of services are mentioned on the home page.
