### ISSUE TITLE
Booking Activities

### ISSUE THREAD

**Issue by Mark1-15** [Mark1-15/project-1#3]
**User story:**
I want to be able to see what sort of activities is available and for what group of people these activities are appropriate for, I may also like to be able to book myself into these activities.

**Assessment Criteria:**

- [x] Separate Activities section/page is available on the page, clearly identifying what sort of activities these are, and for what group of people.
- [x] Activities should be distinguishable from one another.
- [x] The ability to book oneself into these activities.

**Tasks:**

- [x] Using bootstrap cards to showcase separate activities
- [x] Creating a form document to book oneself onto a certain activity on a certain date.
- [x] Creating a separate page for activities.
