### ISSUE TITLE
Engaging images

### ISSUE THREAD

**Issue by Mark1-15** [Mark1-15/project-1#4]
**User story:**
As an artist and graphic designer, I want engaging images on the website, about the activities and theme.

**Acceptance Criteria:**

- [x] Several different images are used on the website showcasing the activities advertised as well as general themes of Hope House.
- [x] Images used are high quality.

**Tasks:**

- [x] Collect and implement engaging photos and implement them via filepath in HTML.
- [x] Ensure the files have been converted to webp for high quality.
