### ISSUE TITLE
Donate button

### ISSUE THREAD

**Issue by Mark1-15** [Mark1-15/project-1#7]
**User story:**
I strongly believe in supporting those who dedicate their time and energy into making the community a better place, and who give up their time and energy in providing enjoyment for others. Therefore, I would like to financially recompense this group of people for what they do. 

**Acceptance Criteria:**

- [ ] A donate button is located on the footer of each page, when clicked will take them to a different page where they can fill in a form with their payment information. 

**Tasks:**

- [ ] Create a new page to accept their payment
- [ ] Create a stylish, welcoming, and friendly donate button on the footer of each page.
