### ISSUE TITLE
Engaging Images

### ISSUE THREAD

**Issue by Mark1-15** [Mark1-15/project-1#8]
**User story:**
As an artist and graphic designer, I want engaging images on the website, about the activities and theme.

**Acceptance Criteria:**

- [x] Several different images are used on the website showcasing the activities advertised as well as general themes of Hope House.

- [x] Images used are high quality, engaging and show the activity.

**Tasks:**

- [x] Collect and implement engaging photos and implement them via filepath in HTML.

- [x] Images used are converted to jpg, jpeg, webp or some other high quality format.
